### ISSUE TITLE
[Bug]: dj menu subwoofer not working

### ISSUE THREAD

**Issue by rezu12123** [CMGStudios/issue-tracker#1232] opened 2024-11-28 15:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the subwoofer doesnt work i have dj license

### Expected behaviour

the subwoofer doesnt work i have dj license

### Steps to reproduce

/djmenu
put youtube link
music doesnt play

### Any Texture Packs? (If so list)

no

### CMG User ID

366551

**Comment by Keegasity** [comment] 2024-12-01 15:28
Hello Rezu,

DJ Menu takes abit of playing around with to get working correctly, for example.

If I wanted to play this song -> https://www.youtube.com/watch?v=ZyhrYis509A&ab_channel=AquaVEVO I would need to modify the URL slightly by removing _channel=AquaVEVO

https://www.youtube.com/watch?v=ZyhrYis509A&ab

Please try this and let me know if you have any other issues.

Thanks,
Keegan

**Comment by packfile** [comment] 2024-12-03 10:52
Duplicate of #1229

**Closed as not planned by packfile** 2024-12-03 10:52 UTC
