### ISSUE TITLE
[Bug]: /drone bugged

### ISSUE THREAD

**Issue by nyzrnyzrnyzr** [CMGStudios/issue-tracker#1192] opened 2024-10-07 21:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

/drone doesnt work anymore 
tps u into the drone instead of putting you in a drone cam
explodes after 5 seconds

https://streamable.com/na3t82

### Expected behaviour

go into a mini drone cam and be able to use thermals or whatever 

### Steps to reproduce

/drone 

### Any Texture Packs? (If so list)

nah

### CMG User ID

1144

**Comment by packfile** [comment] 2024-10-21 12:11
Duplicate of https://github.com/CMGStudios/issue-tracker/issues/1190

**Closed as completed by packfile** 2024-10-21 12:11 UTC
Labels: duplicate
