### ISSUE TITLE
[Bug]: Phone

### ISSUE THREAD

**Issue by Galooga** [CMGStudios/issue-tracker#955] opened 2024-02-24 22:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I take pictures I cannot see the image on my gallery and everyone's profile pictures don't show either.

### Expected behaviour

When I take pictures I cannot see the image on my gallery and everyone's profile pictures don't show either and when I open the phone it is very glitchy and laggy. 

### Steps to reproduce

FN+F1

### Any Texture Packs? (If so list)

No

### CMG User ID

401389

**Comment by packfile** [comment] 2024-02-26 09:34
Thanks for the report, closing as this is a duplicate of #939

**Closed as not planned by packfile** 2024-02-26 09:34 UTC
Labels: duplicate
