### ISSUE TITLE
Number plate bug

### ISSUE THREAD

**Issue by Willbs96** [CMGStudios/issue-tracker#94] opened 2021-07-23 22:21 UTC
**Describe the issue you're facing**

Basically, it makes the number plate bigger on some baller-lock cars and leaves an invisible square around the number plate which is really annoying. I know I'm not the only one having this issue a few friends also have it with their cars. It happens every time you get it out. The only fix is to go Los customs and change the plate then it solves it until you crash it and have to get it out again. I'm not sure if there is a fix for it but it's worth an ask.  Thanks
**Steps to reproduce**

**Expected behaviour**

**Screenshots/Video**
https://prnt.sc/1exqvk1

**Additional context**

I don't think a car dev can sort it. I have spoken to a couple and I don't think its to do with the model as it's been tested on private servers. I think its to do with the greenzone thing when you first get a vehicle out.
**Any Texture Packs (if so list)**

**Perm ID**
452

**Comment by rubbertoe98** [comment] 2021-07-24 11:14
Please provide the spawn of a vehicle where this bug occurs, thanks!

**Comment by Willbs96** [comment] 2021-07-24 11:27
levoragtspxxw  Thanks if you just spawn it in with your admin powers it won't show. It's only if you get it out of a garage. Its something to do with the 5-second greenzone when your first get a car out

**Comment by alfiellds** [comment] 2021-07-27 14:30
Confirmed by @BigBoyReece 

https://streamable.com/8iogbu

**Comment by crazychris2404** [comment] 2022-01-28 12:39
I understand this is still a ongoing issue however it is caused by the vehicle model. In order to resolve this you will need to contact a car developer through discord and they can guide you into resolving this problem.

**Closed by crazychris2404** 2022-01-28 12:39 UTC
Labels: bug, confirmed
