### ISSUE TITLE
I can’t see images on birdy 

### ISSUE THREAD

**Issue by Zkajw** [CMGStudios/issue-tracker#1007] opened 2024-03-25 18:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I can’t seem to see the images on birdy what people have put on 
![image](https://github.com/CMGStudios/issue-tracker/assets/164931437/c00fb1a5-251c-43e7-bc5f-33252b921cfa)

### Expected behaviour

I don’t know 

### Steps to reproduce

I’m not sure 

### Any Texture Packs? (If so list)

No

### CMG User ID

400952

**Comment by crazychris2404** [comment] 2024-03-25 18:53
Confirmed 
Thanks for the report

**Comment by packfile** [comment] 2024-04-17 09:40
Thanks for the report, this should be fixed for any posts created since Monday

**Closed as completed by packfile** 2024-04-17 09:40 UTC
Labels: confirmed, pending-review
