### ISSUE TITLE
[Bug]: stuck under the boat in scuba diving.

### ISSUE THREAD

**Issue by Alexafkfan** [CMGStudios/issue-tracker#467] opened 2022-09-10 06:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When diving into the ocean you get stuck under the boat and cannot move.

Clips: https://medal.tv/games/gta-v/clips/AgJpUaQeUvjMC/d1337Pm3YITQ?invite=cr-MSx1MWQsMjMyOTM2MjEs
https://medal.tv/games/gta-v/clips/AgJpUaQeUvjMC/d1337k91Qm1P?invite=cr-MSxxV28sMjMyOTM2MjEs

### Expected behaviour

You would either be stuck in the water standing in place and unable to move or be swimming in place.

### Steps to reproduce

1. start scuba job
2. get plane crash as search area
3. stop boat in zone
4. Press G to get ready to dive in
5. Press E to dive in 
6. Your now stuck

### Any Texture Packs? (If so list)

No

### CMG User ID

279438

**Comment by packfile** [comment] 2022-09-16 10:21
Hey @Alexafkfan, thanks for the report. I can't reproduce this locally, do you have a list of steps to cause this to happen every time?

**Comment by crazychris2404** [comment] 2022-10-06 13:40
Moved to high priority due to numerous reports of this issue

**Comment by packfile** [comment] 2022-10-13 08:20
Thanks for the report, this should be fixed. Please reopen if this still occurs.

**Closed as completed** 2022-10-13 08:20 UTC
Labels: confirmed
