### ISSUE TITLE
[Bug]: Island not spawning on piloting 

### ISSUE THREAD

**Issue by ItzAlex69** [CMGStudios/issue-tracker#1146] opened 2024-08-21 22:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm doing my piloting and every time I got to the island its never spawns in for me either legal or illegal jobs on cmg public in fact of this i have told admins and i have also done loads of F8 quits and alot of T/ reseton the server but still never works

### Expected behaviour

I'm doing my piloting and every time I got to the island its never spawns in for me either legal or illegal jobs on cmg public in fact of this i have told admins and i have also done loads of F8 quits and alot of T/ reseton the server but still never works

### Steps to reproduce

N/A

### CMG User ID

439661

**Comment by packfile** [comment] 2024-08-21 22:55
Duplicate of #1136

**Closed as not planned by packfile** 2024-08-21 22:55 UTC
