### ISSUE TITLE
[Bug]: INGAME PAYMENT PLAN 

### ISSUE THREAD

**Issue by H4AYCH** [CMGStudios/issue-tracker#987] opened 2024-03-14 22:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I had a car on payment which was a Urus venuum furioso Spawncode FURUS the payment plan was started on 25/02/24 and till this day i haven't received a single payment and it has been over 2 weeks which it should of come back to me as this is now a failed pp can you please sort this

### Expected behaviour

I should have received the car in my garage as this is a bug in the payment plan because he has not made 1 single payment

### Steps to reproduce

1

### CMG User ID

217458

**Comment by packfile** [comment] 2024-04-17 09:26
This vehicle has since been returned on the 16th March (confirmed with logs). This was a week late however, so will be investigated seperately

**Closed as not planned by packfile** 2024-04-17 09:26 UTC
Labels: pending-review
