### ISSUE TITLE
[Bug]: Storing your vehicle after refueling manually removes the added fuel

### ISSUE THREAD

**Issue by TotalXanarchy** [CMGStudios/issue-tracker#491] opened 2022-10-22 11:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you refuel at a petrol station manually using the pump and then store your vehicle in a garage, the next time you get your car out of a garage the fuel will be at the amount it was prior to refilling it.

### Expected behaviour

If I refill my car at a petrol pump and then store it, the car should have 100% fuel in the garage but it doesn't.

### Steps to reproduce

Take a car low on fuel to a petrol station and fill it up manually by parking next to a pump and using the refill car option.

Store the car at a garage.

Take the car out of the garage and it will be at the low fuel amount again.

(Interesting note to mention is the fuel is fine if you let the vehicle get cleaned up by the server, it's only when you store it manually that this issue occurs)

### Any Texture Packs? (If so list)

nope

### CMG User ID

313151

**Comment by crazychris2404** [comment] 2022-10-22 16:47
Hi @TotalXanarchy 
Thanks for the report
This issue is not occurring for me 
Please can you attach a video of this occurring.

**Comment by TotalXanarchy** [comment] 2022-10-22 21:55
Just tried to get a video reproducing this and it's not happening anymore which is strange

**Comment by TotalXanarchy** [comment] 2022-11-12 20:13
This issue is happening again for me now, here's a video https://clipchamp.com/watch/xe0RSBI6DeJ

**Comment by packfile** [comment] 2022-11-13 23:03
> This issue is happening again for me now, here's a video https://clipchamp.com/watch/xe0RSBI6DeJ

Thanks for the updated info, this will be investigated this week

**Comment by TotalXanarchy** [comment] 2022-11-14 14:05
Another observation, it seems to occur if you fuel the car and put it straight back into the garage. If you use a bit of the fuel first it seems to save, maybe the way fuel is saved isn't registering it as full until the number is reduced again?

**Comment by l3x04** [comment] 2022-12-15 12:20
This issue has occurred for me. Seems to be when there is not much time in-between when you store your vehicle/fuel it. A possible fix could be making sure upon payment at the Fuel Stations (As soon as you finish fueling) the % of fuel gets saved.

**Comment by crazychris2404** [comment] 2022-12-16 10:43
Closed due to not currently being reproducible and also being a very rare occurrence

**Closed as completed by crazychris2404** 2022-12-16 10:43 UTC
Labels: cannot reproduce
