### ISSUE TITLE
[Bug]: Invetory closes when i click

### ISSUE THREAD

**Issue by OLIVER0184** [CMGStudios/issue-tracker#957] opened 2024-02-26 14:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i open my inventory try click a item and it closes it 

### Expected behaviour

i have tried fixing it on both inventory's

### Steps to reproduce

1. open inventory 2. click a item 3. closes

### Any Texture Packs? (If so list)

i have none 

### CMG User ID

404024

**Comment by packfile** [comment] 2024-02-26 14:42
Duplicate of #956

**Closed as not planned by packfile** 2024-02-26 14:42 UTC
Labels: duplicate
