### ISSUE TITLE
Car never comes out

### ISSUE THREAD

**Issue by ethznnnn** [CMGStudios/issue-tracker#143] opened 2021-08-14 11:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

my mercedes maybach brabus never pulls out from the garage, it was the same for the previous owner aswell (tailgater2 - spawn code)

### Expected behaviour

Wont pull out from the garage

### Steps to reproduce

Try and pull it out from the garage

### Any Texture Packs? (If so list)

no

### CMG User ID

197224

**Comment by rubbertoe98** [comment] 2021-08-16 16:33
Closing due to duplicate of #140

**Closed by rubbertoe98** 2021-08-16 16:33 UTC
Labels: bug, duplicate
