### ISSUE TITLE
[Bug]: Rented out a house now its gone

### ISSUE THREAD

**Issue by Chokezil** [CMGStudios/issue-tracker#210] opened 2021-09-05 15:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some time ago i rented out a house for a month and when the 30 days were up I lost the ownership of it. This has happened with two houses but one of them were to my mate so he just gave it back. I am certain that I didn't sell the house because I could see the remaining time on the rent manager, but after that it was gone. The problem is I am not sure what the persons name is that I rented it to, so I can ask him to give it back. I have not seen the house being sold after I lost it so I think the guy hasn't noticed or is just happy getting a free house. Also, I cant check who owns it since they removed the whole checking the ownership at the doorstep. The house in question is Mega Luxury n48

### Expected behaviour

The ideal situation would be me getting the house back somehow. Maybe from checking logs of the renting or getting in touch with the "current" owner so I can speak to him.

### Steps to reproduce

Perhaps check if there is some issue with renting out houses longer than 30 days. To reproduce it I guess you could try renting out houses for longer periods and see if the bug still appears

### CMG User ID

18631

**Comment by loganuk** [comment] 2021-09-16 04:54
Need to check rental/transaction logs for this one - Perm ID = 18631

**Comment by loganuk** [comment] 2021-09-17 03:56
Merged issue in from https://github.com/CMGStudios/issue-tracker/issues/221

**Description**
Hi , so before i left cmg i rented my ranch next to casino to el chapo for 3 months since i comeback to cmg i have been surprised that i dont have the owership of my ranch anymore even if the rent expired , This is the first time I have this problem
i guess the rent system got bugget cuz el chapo got banned within this period My perm id : 34042 discord : TheOGMrMoustache#46

![image](https://user-images.githubusercontent.com/47579821/133721741-5f2c4656-1eae-44ef-95fa-7f146b5e8e1d.png)


**Expected behaviour**
i want my ranch back Deviation know already about this issue , you can contact the guy i rented to him my ranch thats his discord : ElChapo#7016

**Steps to reproduce**
maybe check if there is some issue with renting out houses longer than 30 days or if the rent get bugged when the guy who rent it to him is banned within the rent period

**CMG User ID**
34042

**Comment by rubbertoe98** [comment] 2021-09-28 00:33
Mega Luxury n48 is owned by Sp1ce - ID: 492, does this ring a bell?

Issue #221 is was caused by a manual change of ownership so not related I don't think.

**Closed** 2021-09-28 14:27 UTC
Labels: bug, invalid, need info
