### ISSUE TITLE
Female Ped Hair

### ISSUE THREAD

**Issue by jackiiew** [CMGStudios/issue-tracker#103] opened 2021-07-26 03:33 UTC
**Describe the issue you're facing**
For the female ped when you choose a hairstyle past a certain number it doesn’t stay on anytime you relog. 

**Steps to reproduce**

**Expected behaviour**
To load onto the server and have the same hairstyle chosen before logging off. 

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**
None

**Perm ID**
190516

**Comment by alfiellds** [comment] 2021-07-27 14:19
Hello Jackie, I have been unable to reproduce this issue. Could you possibly provide a clip to demonstrate the issue and also the numbers of the hairstyles which do not save upon logging?

Many thanks.

**Comment by loganuk** [comment] 2021-08-03 21:40
The hair options are not a permanent value in the clothing menu - They are meant to be temporary by design - Please use the barber shop for permanent alterations to your player avatar on CMG.

This ticket will be closed in 24 hours if no further information is provided.

**Closed** 2021-08-08 12:28 UTC
Labels: need info
