### ISSUE TITLE
Radios 

### ISSUE THREAD

**Issue by JorPet1** [CMGStudios/issue-tracker#488] opened 2022-10-17 17:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the police radios it is showing the same names multiple times, which may cause misunderstanding

### Expected behaviour

...

### Steps to reproduce

1. t /radios
2. Join PD radio
3. some names will appear multiple times

### Any Texture Packs? (If so list)

Nope

### CMG User ID

605

**Comment by crazychris2404** [comment] 2022-10-18 07:26
Hi @JorPet1 
Thanks for the report 
I have seen multiple other reports of this.
Later today I will look into finding the cause of this

**Comment by packfile** [comment] 2022-10-18 09:42
Thanks for the report, this should be fixed

**Closed as completed** 2022-10-18 09:41 UTC
