### ISSUE TITLE
[Bug]: Natwest Bank Robbery Setup

### ISSUE THREAD

**Issue by XXH41DERX** [CMGStudios/issue-tracker#978] opened 2024-03-08 23:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i do the natwest bank setup on the boat there is always a guard who is inside thge actual model of the boat and it can shoot u but u cant shoot it back so u end up dying.

### Expected behaviour

start the setup
get onto the actual big boat "disabled boat"
be able to kill all guards and not have one in the actual boat
jump off and then have the devices

### Steps to reproduce

1 start the setup in lesters factory
2 drive down to cayo
3 get onto a dinghy
4 grapple onto the boat
5 run around killing all guards

### Any Texture Packs? (If so list)

nope

### CMG User ID

1089

**Comment by packfile** [comment] 2024-06-04 10:44
Collisions for the boat will be fixed soon, it also appears this is quite infrequent
Duplicate of #926

**Closed as not planned by packfile** 2024-06-04 10:44 UTC
Labels: pending-review
