### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Troyoak** [CMGStudios/issue-tracker#753] opened 2023-08-11 21:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When dead if u press esc to get on new pause menu it bugs the respawn and removes the respawn button

### Expected behaviour

Clip:
https://medal.tv/games/gta-v/clips/1oqp3b7mQ5bpuz/d1337tdPvy7r?invite=cr-MSw5N2wsNjk3MjE0MDYs

### Steps to reproduce

die
press esc
cant respawn

### Any Texture Packs? (If so list)

no

### CMG User ID

373070

**Comment by packfile** [comment] 2023-08-11 21:05
Duplicate of #749

**Closed as completed by packfile** 2023-08-11 21:05 UTC
