### ISSUE TITLE
[Bug]: NHS Lifepack stops working

### ISSUE THREAD

**Issue by MrMikeyTV** [CMGStudios/issue-tracker#150] opened 2021-08-17 22:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unfortunately, the lifepack does not work every now and then. This will be hard to replicate. It just stops working altogether. We have tried the following things to try and resolve it but nothing works:
- Relogging
- Clocking on and off
- Pressing U and opening the NHS menu that way

This issue has been ongoing and happens randomly to random people at random times.

Video - https://youtu.be/G_CLI-YApUA

### Expected behaviour

It is supposed to open the NHS menu where you press observations and shock patient would be at the bottom.

### Steps to reproduce

1. Press E on an injured person
2. Press CPR

### CMG User ID

604

**Comment by loganuk** [comment] 2021-08-18 14:08
This bug has been around for some time - If we can get members of the NHS to attempt to re-produce it or document it in testing that would help significantly.

**Comment by MrMikeyTV** [comment] 2021-08-18 16:07
Hi, I've spent a good few hours today with a few people trying to replicate it by spamming commands, reviving several people at once etc. and unfortunately, we're not able to replicate it.

**Comment by loganuk** [comment] 2021-08-19 15:25
I'll leave this issue open for 24 hours - See if anyone from the NHS strikes gold at being able to reproduce this issue.

**Comment by MrMikeyTV** [comment] 2021-08-23 14:32
Just an update on this - we cannot figure it out. It is a randomly sporadic bug. We spent a good 2 hours trying different ranks, different commands, emotes etc. and nothing can reproduce it.

**Comment by rubbertoe98** [comment] 2021-09-03 20:06
Closed due to duplicate of #99

**Closed by rubbertoe98** 2021-09-03 20:06 UTC
Labels: bug, duplicate, confirmed
