### ISSUE TITLE
[Bug]:Pet health and Stuff

### ISSUE THREAD

**Issue by kajblm** [CMGStudios/issue-tracker#539] opened 2022-12-26 16:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I recently purchased a pet and have been noticing that it just dies by the simplest things eg. Tapping the back of a car, tripping over a curb etc.

### Expected behaviour

The pet shouldn’t be dying this easily and maybe needs to be looked at

(Pet monkey)

### Steps to reproduce

No steps really just they die super easy by tripping over 

https://streamable.com/s9v11b

### Any Texture Packs? (If so list)

N/A

### CMG User ID

214124

**Comment by crazychris2404** [comment] 2022-12-27 23:19
I believe this was looked into before but i am unsure if there is a possible fix @tom-gun can provide more info

**Comment by kajblm** [comment] 2022-12-27 23:43
Could it be possible that the monkey just made invincible as it doesn’t deal damage or it doesn’t have an attack function. Just for show

**Comment by packfile** [comment] 2023-01-02 21:55
Duplicate of #237 - This has been looked into a couple times and no reasonable solution has been found

**Closed as not planned by packfile** 2023-01-02 21:55 UTC
Labels: confirmed
