### ISSUE TITLE
give Jxckrundle#0001 his roles

### ISSUE THREAD

**Issue by jxckrundle** [CMGStudios/issue-tracker#120] opened 2021-08-07 20:50 UTC
**Describe the issue you're facing** i have done the forum to get bertified role still have not got it since all the devs have egos![Screenshot 2021-08-07 215008](https://user-images.githubusercontent.com/88597529/128613540-86cef62c-2a8c-4f8e-b96b-e953793852a8.png)
**Steps to reproduce**give me vertified role

**Expected behaviour**

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**no
![Screenshot 2021-08-07 215008](https://user-images.githubusercontent.com/88597529/128613540-86cef62c-2a8c-4f8e-b96b-e953793852a8.png)**Perm ID**201150

**Comment by arthur-rl** [comment] 2021-08-07 20:51
Not a bug report. closing and deleting. 

Oh and by the way. my ego is massive :P

**Closed by arthur-rl** 2021-08-07 20:51 UTC
