### ISSUE TITLE
keep spawning under the map with micheal

### ISSUE THREAD

**Issue by Coolman1156** [CMGStudios/issue-tracker#231] opened 2021-09-27 19:44 UTC
For some reason, every time i log in currently i spawn under the map near Vinewood hills with Michael. It also puts me into the default clothes

**Comment by Drkiller99** [comment] 2021-09-27 21:47
That sounds very hard for them to reproduce, you might wanna post a clip of it for them :)

**Comment by rubbertoe98** [comment] 2021-09-28 15:21
Duplicate of #129

**Closed by rubbertoe98** 2021-09-28 15:21 UTC
Labels: duplicate
