### ISSUE TITLE
[Bug]: cursor stuck on F7 PD menu

### ISSUE THREAD

**Issue by LuciferKronus** [CMGStudios/issue-tracker#485] opened 2022-10-04 17:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When opening the PD F7 menu to issue fines the cursor stays stuck to the middle of the screen cannot use menu to issue fines 

### Expected behaviour

When moving the mouse to click anywhere the cursor snaps back to the middle of the screen.

### Steps to reproduce

Be clocked on PD
Press F7 for fines / crimes menu

### CMG User ID

56498

**Comment by crazychris2404** [comment] 2022-10-04 17:56
Hi @LuciferKronus 
I am unable to reproduce this, please can you provide a clip of this occurring

**Comment by LuciferKronus** [comment] 2022-10-04 18:29
https://youtube.com/shorts/DPsy07eyzZU?feature=share

**Comment by crazychris2404** [comment] 2022-10-05 16:01
How long has this been occuring?
We havent had any other reports of this occuring and neither me or @tom-gun can reproduce this

**Comment by LuciferKronus** [comment] 2022-10-05 16:04
It worked fine on the 27th during my PD training. Ever since then it has been doing the same thing.

**Comment by kajblm** [comment] 2022-10-05 16:38
If your playing on windowed or fullscreen exclusive it could be an issue with the cursor going off your screen etc.

**Comment by LuciferKronus** [comment] 2022-10-05 16:48
I have changed to just full screen and I'm still having the issue.

**Comment by crazychris2404** [comment] 2022-10-06 13:41
What screen resolution are you using @LuciferKronus

**Comment by packfile** [comment] 2022-10-11 14:30
@LuciferKronus Any response to the above? Can you also please confirm what your "Mouse Input Method" is set to under "Keyboard / Mouse" in settings

**Comment by LuciferKronus** [comment] 2022-10-11 14:31
I am no longer able to check as I'm no longer on PD so cannot check to see if it is still bugged out

**Comment by packfile** [comment] 2022-10-11 14:35
Alright, marking closed as there is no further information to be provided and the issue is believed to be isolated to your setup

**Closed as not planned by packfile** 2022-10-11 14:35 UTC
