### ISSUE TITLE
[Bug]: Can't grapple onto boat for door hacking device setup.

### ISSUE THREAD

**Issue by lui22222** [CMGStudios/issue-tracker#951] opened 2024-02-20 22:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you arrive next to the big boat in the setup you get a grapple which lets you grapple onto the boat. When you grapple the grapple just deletes and you don't get grappled anywhere instead staying still. If you later on get onto the boat and kill all the guards it wont let you continue the setup due to the helicopter not spawning. 

### Expected behaviour

.

### Steps to reproduce

Start the 3RD setup at lesters place.

Once setup is started make your way to Cayo Perico. 

Get into a boat and drive it next to the boat aka yellow circle in the water. 

You should recieve a grappler but when you do grapple it wont do anything.

### Any Texture Packs? (If so list)

Non

### CMG User ID

264290

**Comment by packfile** [comment] 2024-04-09 11:06
Thanks for the report, this is believed to have been fixed in March (can't reproduce locally or in live server anymore).

**Closed as completed by packfile** 2024-04-09 11:06 UTC
