### ISSUE TITLE
Spawning under the floor

### ISSUE THREAD

**Issue by RazzaWelshy** [CMGStudios/issue-tracker#58] opened 2021-07-09 00:59 UTC
**Describe the issue you're facing**When loading in I keep spawning under the floor and get stuck underneath the floor and my clothes reset

**Steps to reproduce** Load in

**Expected behavior** Spawn under the floor

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**None

**Perm ID**117744

**Comment by alfiellds** [comment] 2021-07-11 15:35
Hello Razza, thank you for the report. This will be forwarded to the developers for them to review.

**Comment by rubbertoe98** [comment] 2021-07-23 17:25
Cannot reproduce, how often does this happen? Can you post a video? And please post your PC specs too.

**Comment by Xotiic1** [comment] 2021-07-23 17:29
This used to happen to me before I stopped using steam

**Comment by rubbertoe98** [comment] 2021-07-29 13:18
Closing due to being unable to reproduce & no reply after asking for further evidence.

**Closed by rubbertoe98** 2021-07-29 13:18 UTC
Labels: bug, confirmed
