### ISSUE TITLE
[Bug]: business centre 7

### ISSUE THREAD

**Issue by Foooopa** [CMGStudios/issue-tracker#1046] opened 2024-05-07 21:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I just bought business centre number 7 and there is gold piles floating everywhere that i cant remove. Also the base tv with the property doesnt work at all after buying the function

### Expected behaviour

should be able to delete and remove them. make it so i dont have to buy another tv and place it over it to work

### Steps to reproduce

Please just make it so i can remove them or just have them removed by the admins

### Any Texture Packs? (If so list)

no

### CMG User ID

1065

**Comment by packfile** [comment] 2024-05-13 10:15
Duplicate of #1040

**Closed as not planned by packfile** 2024-05-13 10:15 UTC
Labels: duplicate
