### ISSUE TITLE
[Bug]: HMPS Panic Image

### ISSUE THREAD

**Issue by Drkiller99** [CMGStudios/issue-tracker#367] opened 2022-03-07 18:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When HMPS Members panic it's not showing an image.

### Expected behaviour

1. /panic
2. Shows the HMPS Logo on the panic.
Proof: https://prnt.sc/aFHHARuXAbPE

### Steps to reproduce

1. /panic
2. Look at the panic notification image for HMPS.

### Any Texture Packs? (If so list)

I don't use any texture packs.

### CMG User ID

850

**Comment by crazychris2404** [comment] 2022-03-07 18:15
Confirmed 
Thanks for the report.

**Comment by Drkiller99** [comment] 2022-03-07 19:20
No problem :)

**Comment by tom-gun** [comment] 2022-03-07 22:54
Closing as the author has tested in game since and it works fine - most likely an issue with that one panic. If you find a way to reproduce please reopen

**Closed by tom-gun** 2022-03-07 22:54 UTC
Labels: bug, confirmed
